version: "3.8"
services:
  frontend:
    build: frontend
    ports:
      - 8080:8080
  backend:
    build: backend
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://database/kurs"
    ports:
      - 3000:3000
  database:
    image: mongo:6.0
    ports:
      - 37017:27017
    volumes:
      - ./data:/data/db
